default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: profistyle_development


test:
  <<: *default
  database: profistyle_test

production:
  <<: *default
  database: profistyle_prod
  username: deploy
  password: <%= ENV["PROFISTYLE_DATABASE_PASSWORD"] %>
