default: &default
        adapter: postgresql
        encoding: unicode
        pool: 5
        timeout: 5000

      development:
        <<: *default
        host: localhost
        port: 5432
        user: postgres
        database: rubydeploy_dev

      test:
        <<: *default
        host: localhost
        port: 5432
        database: rubydeploy_test

      production:
        <<: *default
        host: localhost
        port: 5432
        database: profistyle_prod
        username: deploy
        password: ahbplf22